### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by AndreasEkstedt**
DRalgo updates:

Bug fixes:
-Fixed Yukawa beta-functions for Dirac Fermions
-Added fermion-mass corrections to Yukawa couplings
-Fixed an issue where sometimes erroneous information would be printed in the PrintCoupling[] command
-Fixed a bug with vector-like fermion beta functions
-Fixed bugs with some non-abelian contributions to the effective potential 

Changes:
-The PrintTensorsVEV[] command (and similar for the other PrintTensor commands) behave slightly differently.
 PrintTensorsVEV[] now gives the available tensors, and PrintTensorsVEV[X] (with X a number) returns the choosen tenssor.

New Features:
-UseSoftTheory[] automatically loads the soft theory for calculating the effective potential
-UseUltraSoftTheory[] automatically loads the ultrasoft theory for calculating the effective potential
-Supplying the option "PerturbativeDiagonalization->True" to CalculatePotentialUS[] treats off-diagonal masses as perturbations
-PrintEffectivePotential[] now prints the full LO+NLO+NNLO effective potential; PrintEffectivePotential["LO"] etc works as before
-Supplying the "Normalization4D->True"  command to  ImportModelDRalgo[] gives effective coupling with 4d normalizations, that is, without extra factors of T, sqrt(T), etc in various couplings.

### CODE REVIEW

**Comment by pschicho** [comment]
Explaining the notation PrepareHET[{},{}] would help in the tripletHET.m file.

**Comment by AndreasEkstedt** [comment]
> Explaining the notation PrepareHET[{},{}] would help in the tripletHET.m file.

Will do.

**Comment by pschicho** [comment]
In NewModel.m the option IncludeCubics->"False" in 
```
PerformDRsoft[{},IncludeCubics->"False"]
```
has no effect.

**Review by pschicho — APPROVED** [review]

**Comment by pschicho** [comment]
All example files passed without error. tripletHET.m should still be tested against Literature but approvable since previous version features are definitely working.

**Pull request merged**
